---
distro: trusty

cache:
  directories:
    - /home/travis/.cache/cargo

services:
  - docker

before_install: make pull
install: make build
script: make test

notifications:
  email:
    on_success: never
    on_failure: never
